"""METHODS.md generator.

Builds an auto-generated methods paragraph describing the EXACT algorithm
chain of this run — only the stages that actually executed are mentioned,
with their resolved parameter values and the re-measured gate numbers.
Citations are self-contained author-year labels — e.g. ``(Bourne et al.
2020)`` — drawn exclusively from constants.METHODS_BIBLIOGRAPHY, so a
reader can see who a method came from and add it to their own
bibliography without a separate reference list.

The text is a copy-paste STARTING POINT for a paper's methods section,
not a substitute for the author's own description — the header says so.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from grainsmith.constants import (
    CELL_PARAM_TOL,
    CHAR_TILT_DEG,
    CHAR_TWIST_DEG,
    COMMENSURATE_TOL,
    LAGB_MAX_DEG,
    METHODS_BIBLIOGRAPHY,
    OVERLAP_DEFAULT_FACTOR,
    WARP_GRAD_MAX,
)
from grainsmith.io.common import Provenance, atomic_writer


def _gate(gates, gate_id: str):
    if gates is None:
        return None
    for r in gates.results():
        if r.gate == gate_id:
            return r
    return None


def _lattice_str(cellpar) -> str:
    parts = [f"a = {cellpar.a:g} Å"]
    if abs(cellpar.b - cellpar.a) > CELL_PARAM_TOL:
        parts.append(f"b = {cellpar.b:g} Å")
    if abs(cellpar.c - cellpar.a) > CELL_PARAM_TOL:
        parts.append(f"c = {cellpar.c:g} Å")
    angles = (cellpar.alpha, cellpar.beta, cellpar.gamma)
    if any(abs(x - 90.0) > CELL_PARAM_TOL for x in angles):
        parts.append("α/β/γ = " + "/".join(f"{x:g}°" for x in angles))
    return ", ".join(parts)


def build_methods_md(
    *,
    config,
    provenance: Provenance,
    crystals: list,
    phase_names: list[str] | None,
    tess,
    msd: float,
    cutoff: float | None,
    n_deleted: int,
    sdot_res=None,
    mdf_res=None,
    gates=None,
    phase_achieved: np.ndarray | None = None,
) -> str:
    """Assemble the METHODS.md text (see the module docstring)."""
    from grainsmith.tessellation.single import SingleCrystalTessellation
    from grainsmith.tessellation.warp import WarpTessellation

    def cite(*keys: str) -> str:
        """Render one parenthesised author-year citation group, e.g.
        ``cite('fractal_gb', 'selfaffine_psd')`` ->
        ``"(Braun et al. 2018; Jacobs et al. 2017)"``. Stateless (no
        numbering/bookkeeping) so the output depends only on the keys
        passed at each call site, keeping the generator deterministic."""
        labels = (METHODS_BIBLIOGRAPHY[k].author_year for k in keys)
        return "(" + "; ".join(labels) + ")"

    triclinic = config.box.cells is not None
    if triclinic:
        H = np.asarray(config.box.resolved_h, dtype=np.float64)
        L = np.diag(H)
    else:
        L = config.box.lengths
    periodic = config.box.periodic
    n = tess.n_grains
    single = isinstance(tess, SingleCrystalTessellation)
    vox_import = config.boundaries.geometry == "voxel_import"
    multiphase = phase_names is not None

    paras: list[str] = []
    paras.append("# Methods")
    paras.append(
        f"> Auto-generated by grainsmith {provenance.version} "
        f"({provenance.timestamp_iso}; seed {provenance.seed}, config "
        f"sha256 {provenance.config_sha12}). This text describes the "
        "algorithm chain of THIS run with its resolved parameters — edit "
        "freely; it is a starting point, not a finished methods section.")

    # --- box ---
    if triclinic:
        n1, n2, n3 = config.box.cells
        geom = (
            f"A restricted-triclinic simulation cell built as "
            f"{n1}×{n2}×{n3} integer multiples of the crystal's own "
            f"conventional cell (box vectors a=({H[0,0]:g}, 0, 0), "
            f"b=({H[0,1]:g}, {H[1,1]:g}, 0), "
            f"c=({H[0,2]:g}, {H[1,2]:g}, {H[2,2]:g}) Å; tilt factors "
            f"xy={H[0,1]:g}, xz={H[0,2]:g}, yz={H[1,2]:g} Å) — the box is "
            "EXACTLY periodic with the crystal lattice by construction "
            "(box.cells), so gate G14 measures zero commensurability "
            "misfit; the cell"
        )
        paras.append(
            f"{geom} contains {n} grain{'s' if n != 1 else ''} and was "
            f"generated with grainsmith {provenance.version}.")
    elif all(periodic):
        geom = "A fully periodic"
    else:
        free = ", ".join("xyz"[k] for k in range(3) if not periodic[k])
        geom = (f"A slab (free along {free}, "
                f"{config.box.vacuum:g} Å vacuum) periodic")
    if not triclinic:
        paras.append(
            f"{geom} simulation cell of {L[0]:g} × {L[1]:g} × {L[2]:g} Å³ "
        f"containing {n} grain{'s' if n != 1 else ''} was generated with "
        f"grainsmith {provenance.version}.")

    # --- crystal / phases ---
    if multiphase:
        assert config.phases is not None
        descs = []
        for p, (pc, c) in enumerate(zip(config.phases, crystals,
                                        strict=True)):
            frag = (f"{pc.name} — {c.dataset['international']} (space "
                    f"group No. {c.dataset['number']}; "
                    f"{_lattice_str(c.cellpar)}), target volume fraction "
                    f"{pc.fraction:g}")
            if phase_achieved is not None:
                frag += f" (achieved {float(phase_achieved[p]):.4f})"
            descs.append(frag)
        paras.append(
            f"The cell contains {len(crystals)} phases: "
            + "; ".join(descs)
            + ". Each phase was expanded from its Wyckoff sites and "
            f"verified by an spglib symmetry round-trip {cite('spglib')} "
            "(gate G2). Grains were partitioned among the phases by a "
            "deterministic greedy (largest-grain-first) assignment of the "
            "measured cell volumes; the achieved volume fractions were "
            "re-measured by gate G15.")
    else:
        c = crystals[0]
        cif_cfg = config.crystal.cif if config.crystal is not None else None
        crystal_para = (
            f"The {c.dataset['international']} structure (space group "
            f"No. {c.dataset['number']}; {_lattice_str(c.cellpar)}) was ")
        if cif_cfg is not None:
            crystal_para += (
                f"read directly from the CIF file {cif_cfg.file} (ASE "
                "parser) with its space group detected by spglib at "
                f"symprec = {cif_cfg.symprec:g} {cite('spglib')} (gate G2); "
                "the symmetry-inequivalent Wyckoff sites were expanded "
                "and re-verified against the same detected group.")
        else:
            crystal_para += (
                "expanded from its Wyckoff sites and verified by an "
                f"spglib symmetry round-trip {cite('spglib')} (gate G2).")
        paras.append(crystal_para)

    # --- seeding ---
    if not single and not vox_import:
        seed_txt = ("Grain centres were placed by random sequential "
                    f"adsorption with a minimum centre separation of "
                    f"{msd:.4g} Å")
        if config.grains.lloyd_iterations > 0:
            seed_txt += (f", followed by {config.grains.lloyd_iterations} "
                         "iterations of Lloyd centroidal relaxation")
        paras.append(seed_txt + ".")

    # --- tessellation ---
    if single:
        g14 = _gate(gates, "G14")
        eps = f"{float(g14.measured):.3g}" if g14 is not None else "n/a"
        commensurate = (g14 is not None
                        and float(g14.measured) <= COMMENSURATE_TOL)
        if commensurate:
            defect_txt = (
                "the lattice is commensurate with the box to within the "
                f"{COMMENSURATE_TOL:g} (dimensionless strain) tolerance, "
                "so the periodic box faces introduce no self-boundary "
                "defect")
        else:
            defect_txt = (
                "the lattice is INCOMMENSURATE with the box beyond the "
                f"{COMMENSURATE_TOL:g} (dimensionless strain) tolerance, "
                "so the periodic box faces are self-boundary defects, "
                "resolved by the overlap-removal stage like any grain "
                "boundary")
        paras.append(
            "The box constitutes a single crystal (one grain spanning the "
            "whole cell; no tessellation). The maximum per-axis "
            "box/lattice commensurability misfit of the rotated lattice "
            f"is ε = {eps} (gate G14); {defect_txt}.")
    elif vox_import:
        vi = config.boundaries.voxel_import
        assert vi is not None
        shape = "×".join(str(s) for s in tess.voxel_grid.shape)
        paras.append(
            f"The grain geometry was imported from an external voxel "
            f"label field ({vi.file}; {shape} voxels, {n} grains) and "
            "atomized directly — per-axis fundamental windows around the "
            "minimum-image grain centroids preserve the exact one-cover "
            "tiling of the periodic cell.")
    else:
        curved_cfg = (config.boundaries.curved
                      if config.boundaries.geometry == "curved" else None)
        warp_base = (curved_cfg.base
                     if curved_cfg is not None and curved_cfg.method == "warp"
                     else None)
        if sdot_res is not None:
            sd = config.grains.size_distribution
            assert sd is not None
            tess_txt = (
                "Grain shapes follow a Laguerre (power) tessellation "
                f"{cite('laguerre_volumes', 'sdot_periodic')} whose "
                "weights were fitted by damped-Newton semi-discrete "
                f"optimal transport {cite('sdot_newton')} "
                f"({sdot_res.iterations} iterations) so the cell volumes "
                f"match {sd.type} targets to a maximum relative error of "
                f"{sdot_res.max_rel_error:.2e} (gate G11)")
            if sd.centroidal_iterations > 0:
                tess_txt += (
                    f", alternated with {sd.centroidal_iterations} "
                    "centroidal (seed-to-centroid) outer iterations "
                    f"{cite('centroidal_laguerre')}")
        elif warp_base == "additive_weights":
            assert curved_cfg is not None
            tess_txt = (
                "Grain shapes follow an additive-weight (Johnson–Mehl) "
                f"diagram of the seed points (weight spread σ_w = "
                f"{curved_cfg.weight_sigma:g} Å), used here as the "
                "pre-warp base tessellation")
        elif warp_base == "anisotropic":
            assert curved_cfg is not None
            lo, hi = curved_cfg.aspect_ratio_range
            tess_txt = (
                "Grain shapes follow a per-grain ellipsoidal-metric "
                f"(anisotropic) diagram of the seed points (aspect ratios "
                f"in [{lo:g}, {hi:g}]), used here as the pre-warp base "
                "tessellation")
        else:
            tess_txt = (
                "Grain shapes follow the periodic Voronoi tessellation of "
                "the seed points (Qhull), the standard space-filling "
                "model of equiaxed polycrystals as used by "
                f"state-of-practice generators {cite('neper')}")
        if config.boundaries.geometry == "curved":
            curved = curved_cfg
            assert curved is not None
            if curved.method == "warp":
                # warp accepts spectrum: gaussian only (a coordinate
                # diffeomorphism cannot produce a genuinely self-affine
                # boundary regardless of Hurst exponent, so self_affine
                # is not a valid warp spectrum — docs/physics.md §5b);
                # this paragraph does not branch on curved.spectrum.
                grad = (f"{tess.grad_max:.3f}"
                        if isinstance(tess, WarpTessellation) else "n/a")
                tess_txt += (
                    ". Boundaries were curved by a divergence-free domain "
                    "warp u(x) sampled from a periodic Gaussian random "
                    f"field (RMS amplitude {curved.amplitude:g} Å per "
                    "component; bijectivity guard max‖∇u‖ = "
                    f"{grad} < {WARP_GRAD_MAX:g}, gate G6) with "
                    f"correlation length {curved.correlation_length:g} Å")
            elif curved.method == "additive_weights":
                tess_txt += (
                    ", generalized to an additive-weight (Johnson–Mehl) "
                    f"diagram with weight spread σ_w = "
                    f"{curved.weight_sigma:g} Å")
            elif curved.method == "perturbed_distance":
                # amplitude_convention: curved.amplitude means a DIFFERENT
                # physical quantity depending on convention -- total-band
                # RMS (the legacy default) vs. RMS at one named reference
                # wavelength -- so the
                # generated text must say which, not label both
                # identically as "RMS amplitude" (a silently-wrong
                # methods paragraph is worse than a verbose one).
                convention = getattr(curved, "amplitude_convention", "total_rms")
                if convention == "reference_wavelength":
                    ref_wl = getattr(tess, "reference_wavelength", curved.l_max)
                    amp_txt = (
                        f"RMS amplitude {curved.amplitude:g} Å at the "
                        f"{ref_wl:g} Å reference wavelength (equivalent "
                        f"whole-band RMS amplitude "
                        f"{tess.amplitude_total_rms:g} Å, κ = "
                        f"{tess.kappa:.4g})"
                    )
                else:
                    amp_txt = f"RMS amplitude {curved.amplitude:g} Å"
                tess_txt += (
                    ", replaced by a perturbed-distance level-set "
                    "assignment argmin_i[d(x,s_i) − A·η_i(x)] with an "
                    f"independent per-grain scalar field ({amp_txt})")
                if curved.spectrum == "self_affine":
                    g13 = _gate(gates, "G13")
                    h_est = (f"{float(g13.measured):.3f}"
                             if g13 is not None else "n/a")
                    g20 = _gate(gates, "G20")
                    db_est = (f"{float(g20.measured):.3f}"
                             if g20 is not None
                             and np.isfinite(g20.measured) else "n/a")
                    tess_txt += (
                        ". The per-grain fields follow the band-limited "
                        "self-affine power law √Φ(k) ∝ k^(−(3+2H)/2) with "
                        f"Hurst exponent H = {curved.hurst:g} for "
                        f"wavelengths {curved.l_min:g}–{curved.l_max:g} Å "
                        f"{cite('fractal_gb', 'selfaffine_psd', 'fractal_substrates')}"
                        f" (Hurst back-estimated from the synthesized "
                        f"fields is Ĥ = {h_est}, gate G13); unlike a "
                        "domain warp (a bijective coordinate map, which "
                        "cannot alter the flat-Voronoi surface's fractal "
                        "dimension), this level-set rule can produce a "
                        "genuinely self-affine boundary. Following the "
                        "box-counting protocol "
                        f"{cite('braun2020fractal')}, the box-counting "
                        "roughness index "
                        "estimated from 2D cross-sections over the "
                        f"synthesis band is D_b = {db_est} (flat-Voronoi "
                        "limit D_b = 1.000, gate G20); at MD-typical "
                        "grain sizes/synthesis-band widths this is "
                        "evidence of local cross-section roughness, not "
                        "a converged, large-effect-size fractal-dimension "
                        "measurement (docs/physics.md §5b)")
                reassigned = getattr(tess, "reassigned_fraction", None)
                if reassigned is not None:
                    tess_txt += (
                        f"; periodic connectivity was repaired by "
                        f"reassigning {reassigned:.3%} of voxels to their "
                        "most-contacted neighbor (gate G19)")
            else:
                lo, hi = curved.aspect_ratio_range
                tess_txt += (
                    ", generalized to a per-grain ellipsoidal-metric "
                    "(anisotropic) diagram with aspect ratios in "
                    f"[{lo:g}, {hi:g}]")
        paras.append(tess_txt + ".")

    # --- orientation ---
    o = config.orientation
    if o.scheme == "random_uniform":
        ori_txt = ("Grain orientations were drawn Haar-uniformly from "
                   "SO(3)")
    elif o.scheme == "fiber":
        assert o.fiber is not None
        axis = " ".join(f"{v:g}" for v in o.fiber.crystal_axis)
        ori_txt = (
            f"Grain orientations were sampled around a ⟨{axis}⟩ ∥ "
            f"{o.fiber.sample_direction} fiber with {o.fiber.spread_deg:g}° "
            "Gaussian angular spread")
    elif o.scheme == "odf_components":
        assert o.components is not None
        n_euler = sum(1 for c in o.components if c.euler_bunge_deg is not None)
        n_fiber = sum(1 for c in o.components if c.fiber is not None)
        n_random = sum(1 for c in o.components if c.random)
        mix_parts = []
        if n_euler:
            mix_parts.append(
                f"{n_euler} Euler-angle centre{'s' if n_euler != 1 else ''} "
                "(isotropic spread under the exact Haar sin²(θ/2) "
                "correction where configured)")
        if n_fiber:
            mix_parts.append(
                f"{n_fiber} fiber component{'s' if n_fiber != 1 else ''}")
        if n_random:
            mix_parts.append(
                f"{n_random} Haar-uniform random component"
                f"{'s' if n_random != 1 else ''}")
        ori_txt = (
            f"Grain orientations were sampled from {len(o.components)} "
            "weighted texture components (categorical draw ∝ weight): "
            + "; ".join(mix_parts))
    elif o.scheme == "imported":
        ori_txt = ("Grain orientations were read from the imported "
                   "field's per-grain average Euler angles")
    else:  # fixed / from_list
        ori_txt = ("Grain orientations were prescribed explicitly "
                   f"(scheme '{o.scheme}')")
    if mdf_res is not None:
        assert o.mdf_target is not None
        drift_clause = (
            "annealing ran with a hard cap of "
            f"{o.mdf_target.odf_drift_max:g} on that drift"
            if o.mdf_target.odf_drift_max is not None else
            "the drift was measured (uncapped) during annealing"
        )
        ori_txt += (
            ". The grain-to-orientation assignment was annealed "
            f"({mdf_res.n_steps} swap moves) toward a "
            f"{o.mdf_target.type} target for the boundary-area-weighted "
            "disorientation-ANGLE distribution — a one-dimensional "
            "marginal of the full misorientation distribution; no "
            "misorientation-axis condition enters the objective (true CSL "
            "character, including the ⟨111⟩ axis condition, is reported "
            "independently, gate G23). The anneal only permutes which "
            "grain receives which orientation from the fixed sampled set: "
            "the number-weighted orientation distribution is invariant "
            "under such permutations, while the volume-weighted "
            "orientation distribution function (ODF) is not in general — "
            + drift_clause + ", and the final drift is re-measured on the "
            "final structure (gate G22). The boundary network is reported "
            "against the deterministic Haar-random disorientation-angle "
            "reference of the crystal point group (the Mackenzie law in "
            f"the cubic case) {cite('mackenzie')} (gate G12)")
    paras.append(ori_txt + ".")

    # --- fill + overlap ---
    fill_txt = (
        "Each grain was filled by direct lattice enumeration of its "
        "compact home cell; home cells tile the periodic cell exactly "
        "once, so any — also incommensurate — lattice orientation yields "
        "each lattice point exactly once, with no wrap-and-deduplicate "
        "step.")
    if cutoff is not None:
        ov = config.boundaries.overlap_removal
        fill_txt += (
            f" Inter-grain atom pairs closer than {cutoff:.4g} Å "
            f"(cutoff '{ov.cutoff}', default factor "
            f"{OVERLAP_DEFAULT_FACTOR:g}·d_nn) were resolved by the "
            f"'{ov.policy}' policy, deleting {n_deleted} atoms; the final "
            "minimum inter-grain distance was re-verified (gate G7).")
    else:
        fill_txt += " Overlap removal was disabled."
    paras.append(fill_txt)

    # --- doping ---
    if config.doping is not None:
        n_dop = len(config.doping.dopants)
        names = ", ".join(d.element for d in config.doping.dopants)
        paras.append(
            f"After overlap removal, {n_dop} dopant species ({names}) "
            "were inserted deterministically from a dedicated per-grain "
            "random stream family: substitutional dopants replace host "
            "atoms in place and interstitial dopants occupy "
            "crystallographic interstices of each grain's own lattice "
            "and orientation, with candidate sites rejected inside the "
            "per-dopant minimum-distance cutoff.  GB segregation uses a "
            "two-level shell/bulk Bernoulli model (target enrichment "
            "E = c_shell/c_bulk); target concentrations are atom "
            "fractions of the final structure "
            "(n_dopant / n_total_after_doping) and per-grain placement "
            "is tabulated in doping.csv.  Gate G17 (warn) compares "
            "achieved dopant fractions and enrichment to their targets; "
            "gate G18 (hard) re-verifies the minimum-distance "
            "constraint on the final structure.")

    # --- analysis ---
    ana: list[str] = []
    if config.analysis.csl:
        ana.append(
            "Boundaries were classified against the cubic "
            "coincidence-site-lattice table under the Brandon criterion "
            f"Δθ ≤ 15°·Σ^(−1/2) {cite('brandon', 'csl_table')}.")
    if config.analysis.gb_character:
        ana.append(
            "Each boundary was classified as twist "
            f"(ψ < {CHAR_TWIST_DEG:g}°), tilt (ψ > {CHAR_TILT_DEG:g}°), "
            "or mixed, where ψ is the angle between the physical "
            "misorientation axis and the mean boundary normal"
            + (" (cross-phase pairs are labeled 'interphase' instead)"
               if multiphase else "")
            + ", with boundary-plane Miller indices reported in both "
            "grains' crystal frames (boundaries.csv).")
    if not multiphase:
        ana.append(
            "The boundary misorientation-angle distribution is reported "
            "against a deterministic Haar-random disorientation-angle "
            "reference of the crystal point group (the Mackenzie law in "
            f"the cubic case) {cite('mackenzie')} (mdf.csv).")
    else:
        ana.append(
            "Misorientation-angle distributions are reported per phase "
            "against each phase's deterministic Haar-random "
            "disorientation-angle reference (the Mackenzie law for cubic "
            f"phases) {cite('mackenzie')} (mdf_<phase>.csv); "
            "interphase boundaries carry per-frame habit-plane Miller "
            "indices instead of a misorientation.")
    if config.analysis.statistics:
        ana.append(
            "Grain-size statistics (equivalent-sphere diameters with a "
            "log-normal fit), Wadell sphericity, grain-boundary area per "
            "volume S_V, triple-junction line length per volume L_V, and "
            f"boundary-character area fractions (LAGB < {LAGB_MAX_DEG:g}°) "
            "are tabulated in statistics.csv; the complete "
            "machine-readable record of the run is microstructure.json.")
    if config.analysis.gb_curvature:
        g16 = _gate(gates, "G16")
        drop = (f"{float(g16.measured):.3%}" if g16 is not None
                else "n/a")
        g21 = _gate(gates, "G21")
        gb_resid = (f"{float(g21.measured):.3g}" if g21 is not None
                    else "n/a")
        ana.append(
            "Local grain-boundary mean and Gaussian curvatures (H, K) "
            "were evaluated at the boundary sample points by central "
            "differences of the implicit level set of the margin "
            f"difference {cite('goldman2005')}; area-weighted "
            "per-boundary statistics are appended to boundaries.csv and "
            "the local samples written to gb_curvature.csv.  Sign: "
            "H > 0 means grain_i is locally convex; a per-grain "
            "histogram selects rows with grain_i == g or grain_j == g "
            "and negates H where g == grain_j.  Flat geometries are "
            "planar and report H = K = 0 exactly.  Curvature "
            "magnitudes beyond 1/(2h) of the analysis-grid voxel "
            "spacing h are not resolvable; degenerate samples are "
            f"reported by gate G16 (dropped fraction {drop}).  Because "
            "the estimator samples curvature only at face-interior "
            "points (edges/vertices, where the polyhedral surface is "
            "not twice-differentiable, are excluded), the per-grain "
            "Gauss-Bonnet closure ∮_S K dA = 4π·(1−g) is not expected "
            "to hold on the retained samples; gate G21 reports the "
            f"worst-grain face-interior residual |Σ K·dA| = {gb_resid} "
            "as a coarse fidelity signal on this curvature estimator, "
            "not on the generated geometry (already certified "
            "independently by gates G3/G4/G7).")
    paras.append(" ".join(ana))

    # --- reproducibility ---
    paras.append(
        f"All stochastic stages draw from a single master seed "
        f"({provenance.seed}) through named child streams, independent of "
        "the number of worker processes. Re-running this configuration on "
        "the same machine (BLAS vendor, CPU family) with the pinned "
        "library set (constraints-repro.txt) reproduces every output "
        "byte-for-byte (timestamps aside); a different BLAS build or CPU "
        "keeps the same grains, atom count, species and gate values but "
        "perturbs a minority of coordinates by ~1 ulp, so the digests "
        "differ without any physical change; different numpy/scipy/"
        "spglib versions carry no reproducibility guarantee at all. "
        "`grainsmith verify <outdir>` re-derives both digests from the "
        "shipped files for independent checking.")

    return "\n\n".join(paras) + "\n"


def write_methods_md(path: Path, **kwargs) -> Path:
    """Write METHODS.md (UTF-8, ``\\n`` line ends, byte-identical across
    re-runs of the same config)."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with atomic_writer(path) as fh:
        fh.write(build_methods_md(**kwargs))
    return path
